Repository auth0/nextjs-auth0, pull requests merged in 2020-11, with the labels that each got.

#187 Add frontend hook
  .eslintrc
  examples/api-call-example/components/header.jsx
  examples/api-call-example/components/layout.jsx
  examples/api-call-example/components/with-auth.jsx
  examples/api-call-example/lib/user.jsx
  examples/api-call-example/pages/_app.jsx
  examples/api-call-example/pages/about.jsx
  examples/api-call-example/pages/index.jsx
  examples/api-call-example/pages/profile-ssr.jsx
  examples/api-call-example/pages/profile.jsx
  examples/api-call-example/pages/protected-page.jsx
  examples/api-call-example/pages/shows.jsx
  examples/basic-example/.npmrc
  examples/basic-example/components/header.jsx
  examples/basic-example/components/layout.jsx
  examples/basic-example/components/with-auth.jsx
  examples/basic-example/lib/auth0.js
  examples/basic-example/lib/user.js
  examples/basic-example/package-lock.json
  examples/basic-example/package.json
  examples/basic-example/pages/_app.jsx
  examples/basic-example/pages/about.jsx
  examples/basic-example/pages/index.jsx
  examples/basic-example/pages/profile-ssr.jsx
  examples/basic-example/pages/profile.jsx
  examples/basic-example/pages/protected-page.jsx
  examples/typescript-example/.npmrc
  examples/typescript-example/components/header.tsx
  examples/typescript-example/components/layout.tsx
  examples/typescript-example/components/login-redirect.tsx
  examples/typescript-example/components/with-auth.tsx
  examples/typescript-example/lib/auth0.ts
  examples/typescript-example/lib/user.tsx
  examples/typescript-example/package.json
  examples/typescript-example/pages/_app.tsx
  examples/typescript-example/pages/about.tsx
  examples/typescript-example/pages/index.tsx
  examples/typescript-example/pages/profile-ssr.tsx
  examples/typescript-example/pages/profile.tsx
  examples/typescript-example/pages/protected-page.tsx
  src/hooks/use-user.tsx
  src/index.browser.ts
  src/index.ts
Labels: CH: Added, review:medium

#188 Add frontend hook tests [SDK-2117]
  .eslintrc
  package-lock.json
  package.json
  src/hooks/use-user.tsx
  tests/helpers/hooks.tsx
  tests/hooks/use-user.test.tsx
Labels: review:small

#190 Add integration tests [SDK-2059]
  .circleci/config.yml
  .github/workflows/ci.yml
  .gitignore
  cypress.json
  cypress/integration/smoke.test.ts
  cypress/tsconfig.json
  examples/api-call-example/components/header.jsx
  examples/api-call-example/pages/index.jsx
  examples/api-call-example/pages/profile-ssr.jsx
  examples/api-call-example/pages/profile.jsx
  examples/basic-example/components/header.jsx
  examples/basic-example/pages/index.jsx
  examples/basic-example/pages/profile-ssr.jsx
  examples/basic-example/pages/profile.jsx
  examples/sample-api/package-lock.json
  examples/sample-api/package.json
  examples/typescript-example/components/header.tsx
  examples/typescript-example/pages/index.tsx
  examples/typescript-example/pages/profile-ssr.tsx
  examples/typescript-example/pages/profile.tsx
  package-lock.json
  package.json
Labels: review:small

#191 [SDK-2057] Express mw tests
  examples/typescript-example/package.json
  package-lock.json
  package.json
  src/auth0-session/client.ts
  src/auth0-session/config.ts
  src/auth0-session/cookie-store.ts
  src/auth0-session/get-config.ts
  src/auth0-session/handlers/callback.ts
  src/auth0-session/handlers/login.ts
  src/auth0-session/hooks/get-login-state.ts
  src/auth0-session/index.ts
  src/auth0-session/transient-store.ts
  src/auth0-session/utils/cookies.ts
  src/handlers/login.ts
  src/instance.node.ts
  tests/auth0-session/client.test.ts
  tests/auth0-session/config.test.ts
  tests/auth0-session/cookie-store.test.ts
  tests/auth0-session/fixture/cert.ts
  tests/auth0-session/fixture/helpers.ts
  tests/auth0-session/fixture/https.ts
  tests/auth0-session/fixture/server.ts
  tests/auth0-session/fixture/well-known.json
  tests/auth0-session/handlers/callback.test.ts
  tests/auth0-session/handlers/login.test.ts
  tests/auth0-session/handlers/logout.test.ts
  tests/auth0-session/transient-store.test.ts
  tests/auth0-session/utils/cookie.test.ts
  tsconfig.build.json
Labels: review:large
