Repository auth0/nextjs-auth0, pull requests merged in 2021-03, with the labels that each got.

#317 Fix missing basePath [SDK-2373]
  src/frontend/with-page-auth-required.tsx
  src/handlers/callback.ts
  tests/frontend/with-page-auth-required.test.tsx
Labels: CH: Fixed, review:small

#318 Update dependencies
  examples/kitchen-sink-example/package.json
  package-lock.json
  package.json
Labels: review:tiny

#325 Export context for stubbing default Provider behaviour
  src/frontend/use-user.tsx
  tests/frontend/use-user.test.tsx
Labels: review:small

#334 Release 1.2.0
  CHANGELOG.md
  docs/assets/js/search.js
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.baseconfig.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  docs/modules/version.html
  package-lock.json
  package.json
  src/version.ts
Labels: review:small

#341 Only run integration tests if not on a forked PR [SDK-2406]
  .circleci/config.yml
Labels: review:tiny

#343 [SDK-2405] Organisations support
  src/config.ts
  src/handlers/callback.ts
  src/handlers/login.ts
  src/index.ts
  tests/config.test.ts
  tests/fixtures/setup.ts
  tests/handlers/callback.test.ts
  tests/handlers/login.test.ts
Labels: review:medium
