Repository auth0/nextjs-auth0, pull requests merged in 2021-02, with the labels that each got.

#263 Split configuration into Next and Base config
  README.md
  V1_MIGRATION_GUIDE.md
  src/auth0-session/config.ts
  src/auth0-session/get-config.ts
  src/auth0-session/handlers/callback.ts
  src/auth0-session/handlers/login.ts
  src/auth0-session/handlers/logout.ts
  src/auth0-session/index.ts
  src/config.ts
  src/handlers/callback.ts
  src/handlers/login.ts
  src/handlers/logout.ts
  src/index.ts
  src/session/get-access-token.ts
  src/session/session.ts
  tests/auth0-session/client.test.ts
  tests/auth0-session/config.test.ts
  tests/auth0-session/fixtures/helpers.ts
  tests/auth0-session/handlers/logout.test.ts
  tests/config.test.ts
  tests/fixtures/default-settings.ts
  tests/session/session.test.ts
Labels: review:medium

#266 Update Vercel configuration docs
  examples/README.md
Labels: documentation, review:medium

#268 Simplified configuration of custom login URL [SDK-2264]
  src/config.ts
  src/frontend/use-user.tsx
  src/handlers/profile.ts
  src/helpers/with-page-auth-required.ts
  src/index.ts
  src/session/get-access-token.ts
  tests/config.test.ts
  tests/fixtures/test-app/pages/_document.tsx
  tests/helpers/with-page-auth-required.test.ts
  tests/session/session.test.ts
Labels: review:small

#269 Updated docs [SDK-2263]
  EXAMPLES.md
  README.md
  V1_MIGRATION_GUIDE.md
  cypress/integration/smoke.test.ts
  src/config.ts
  src/handlers/auth.ts
  src/handlers/callback.ts
Labels: review:small

#272 Release 1.0.0-beta.1
  CHANGELOG.md
  docs/assets/js/search.js
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/index.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.config-1.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.usercontext.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/interfaces/session_session.claims.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  docs/modules/session_session.html
  docs/modules/utils_errors.html
  docs/modules/version.html
  package-lock.json
  package.json
  src/version.ts
Labels: review:small

#276 Adding `afterRefetch` hook
  src/handlers/callback.ts
  src/handlers/index.ts
  src/handlers/profile.ts
  src/index.ts
  tests/handlers/profile.test.ts
Labels: review:medium

#280 Update dependencies
  package-lock.json
  package.json
Labels: review:tiny

#284 Missing docs page
  docs/interfaces/config.baseconfig.html
Labels: review:tiny

#286 Add Refresh Token advice to the API example
  EXAMPLES.md
Labels: review:tiny

#287 Release 1.0.0 beta.2
  CHANGELOG.md
  docs/assets/css/main.css
  docs/assets/js/main.js
  docs/assets/js/search.js
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.baseconfig.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  docs/modules/version.html
  package-lock.json
  package.json
  src/version.ts
Labels: review:tiny

#292 Update external API example
  EXAMPLES.md
Labels: review:tiny

#290 Release 1.0.0
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/report_a_bug.md
  .github/PULL_REQUEST_TEMPLATE.Md
  CHANGELOG.md
  README.md
  V1_MIGRATION_GUIDE.md
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/index.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.baseconfig.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/interfaces/session_session.claims.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  docs/modules/session_session.html
  docs/modules/utils_errors.html
  docs/modules/version.html
  package-lock.json
  package.json
  src/session/get-access-token.ts
  src/version.ts
  typedoc.js
Labels: review:small

#301 Chunked cookies should not exceed browser max
  src/auth0-session/cookie-store.ts
  tests/auth0-session/cookie-store.test.ts
Labels: review:medium

#300 Clean the dist folder before building
  package-lock.json
  package.json
Labels: review:tiny

#307 [SDK-2330] New tokens should be applied to existing session
  src/session/get-access-token.ts
  tests/fixtures/setup.ts
  tests/handlers/profile.test.ts
Labels: review:medium

#303 We should cleanup unused cookies when switching between chunked and unchunked
  src/auth0-session/cookie-store.ts
  tests/auth0-session/cookie-store.test.ts
Labels: review:medium

#310 Release v1.1.0
  CHANGELOG.md
  docs/assets/js/search.js
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.baseconfig.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  docs/modules/version.html
  package-lock.json
  package.json
  src/version.ts
Labels: review:tiny
