Repository auth0/nextjs-auth0, pull requests merged in 2021-01, with the labels that each got.

#219 Fix API docs snippets
  EXAMPLES.md
  src/auth0-session/config.ts
  src/config.ts
  src/frontend/with-page-auth-required.tsx
  src/handlers/auth.ts
  src/handlers/callback.ts
  src/handlers/login.ts
  src/helpers/with-api-auth-required.ts
  src/helpers/with-page-auth-required.ts
Labels: review:small

#221 Documentation updates
  README.md
  src/config.ts
Labels: documentation

#223 [SDK-2229] Migration guide
  README.md
  V1_MIGRATION_GUIDE.md
  examples/README.md
  examples/basic-example/README.md
Labels: review:small

#224 Update dependencies
  EXAMPLES.md
  README.md
  V1_MIGRATION_GUIDE.md
  cypress/integration/smoke.test.ts
  package-lock.json
  package.json
  src/frontend/use-user.tsx
Labels: review:small

#229 Added error handling to useUser [SDK-2236]
  EXAMPLES.md
  README.md
  examples/basic-example/pages/index.jsx
  examples/basic-example/pages/protected-page.jsx
  examples/kitchen-sink-example/pages/index.tsx
  examples/kitchen-sink-example/pages/profile.tsx
  src/frontend/index.ts
  src/frontend/use-user.tsx
  src/frontend/with-page-auth-required.tsx
  src/index.browser.ts
  src/index.ts
  tests/fixtures/frontend.tsx
  tests/frontend/use-user.test.tsx
  tests/frontend/with-page-auth-required.test.tsx
Labels: review:medium

#231 Improve syntax highlighting in Readme and Examples
  EXAMPLES.md
  README.md
  src/frontend/use-user.tsx
Labels: review:small

#232 Disable x-powered-by by header
  examples/basic-example/next.config.js
  examples/kitchen-sink-example/next.config.js
Labels: review:tiny

#235 Bump @serverless-jwt/next to resolve some vulnerable deps
  examples/kitchen-sink-example/package.json
Labels: review:tiny

#234 Make smoke tests more resilient
  cypress.json
  cypress/integration/smoke.test.ts
  cypress/support/index.js
  examples/basic-example/components/header.jsx
  examples/basic-example/pages/index.jsx
  examples/kitchen-sink-example/components/header.tsx
  examples/kitchen-sink-example/components/layout.tsx
  examples/kitchen-sink-example/pages/index.tsx
  examples/kitchen-sink-example/pages/profile-ssr.tsx
  examples/kitchen-sink-example/pages/profile.tsx
  examples/kitchen-sink-example/pages/shows.tsx
Labels: review:small

#238 Updated dev dependencies
  package-lock.json
  package.json
  tests/setup.ts
Labels: review:tiny

#242 Update dev dependencies of kitchen sink example
  examples/kitchen-sink-example/package.json
Labels: review:tiny

#246 Added checkSession method to useUser hook [SDK-2256]
  examples/kitchen-sink-example/pages/profile-ssr.tsx
  src/frontend/use-user.tsx
  src/index.browser.ts
  tests/frontend/use-user.test.tsx
  tests/frontend/with-page-auth-required.test.tsx
Labels: review:small

#255 [SDK-2259] Remove env var dependency at build time
  src/helpers/with-page-auth-required.ts
  src/index.ts
  tests/index.test.ts
Labels: review:small

#256 Update the experimental labeling on master
  README.md
Labels: review:tiny

#257 [SDK-2258] Prevent custom session props being removed when refreshing AT
  src/session/get-access-token.ts
  tests/session/get-access-token.test.ts
Labels: review:small

#260 Release 0.16.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/version.ts
Labels: review:tiny

#262 Added internal useConfig hook [SDK-2264]
  src/frontend/index.ts
  src/frontend/use-config.tsx
  src/frontend/use-user.tsx
  src/frontend/with-page-auth-required.tsx
  tests/fixtures/frontend.tsx
  tests/frontend/use-config.test.ts
  tests/frontend/use-user.test.ts
  tests/frontend/with-page-auth-required.test.tsx
  typedoc.js
Labels: review:medium
