Repository auth0/nextjs-auth0, pull requests merged in 2021-09, with the labels that each got.

#483 Add `screen_hint` auth param
  src/handlers/login.ts
Labels: review:tiny

#486 Use the new release automation solution
  .shiprc
Labels: review:tiny

#507 [SDK-2529] Add ability to pass custom params to refresh grant and code exchange
  src/auth0-session/handlers/callback.ts
  src/handlers/callback.ts
  src/session/get-access-token.ts
  tests/handlers/callback.test.ts
  tests/session/get-access-token.test.ts
Labels: review:medium

#508 [SDK-2818] Export error classes
  src/handlers/callback.ts
  src/handlers/login.ts
  src/handlers/logout.ts
  src/handlers/profile.ts
  src/index.ts
  src/session/get-access-token.ts
Labels: review:small
