Repository auth0/nextjs-auth0, pull requests merged in 2021-08, with the labels that each got.

#474 Add an example for signup
  EXAMPLES.md
Labels: review:small

#469 Add a note to the README about the Link component
  README.md
Labels: review:tiny

#476 Update joi to v17.4.2
  package-lock.json
Labels: dependencies

#468 Add org_id optional claim
  src/frontend/use-user.tsx
Labels: review:tiny
