Repository auth0/nextjs-auth0, pull requests merged in 2021-04, with the labels that each got.

#363 [SDK-2456] Remove Organizations beta labelling
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.baseconfig.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.nextconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_callback.callbackoptions.html
  docs/interfaces/handlers_login.authorizationparams.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  src/config.ts
  src/handlers/login.ts
Labels: documentation

#365 [SDK-2452] returnTo should be encoded as it contains url unsafe chars
  src/frontend/with-page-auth-required.tsx
  src/helpers/with-page-auth-required.ts
  tests/frontend/with-page-auth-required.test.tsx
  tests/helpers/with-page-auth-required.test.ts
Labels: review:small

#370 Use `window.location.toString()` as the default `returnTo` value [SDK-2453]
  src/frontend/with-page-auth-required.tsx
  tests/frontend/use-config.test.ts
  tests/frontend/use-user.test.tsx
  tests/frontend/with-page-auth-required.test.tsx
Labels: CH: Fixed, review:small

#375 Bump jose
  package-lock.json
  package.json
Labels: review:tiny
