Repository auth0/nextjs-auth0, pull requests merged in 2021-06, with the labels that each got.

#405 [SDK-2586] Add `user` to `withPageAuthRequiredProps` CSR to match SSR
  examples/kitchen-sink-example/pages/profile.tsx
  src/frontend/index.ts
  src/frontend/with-page-auth-required.tsx
  src/helpers/with-page-auth-required.ts
  src/index.ts
  tests/frontend/with-page-auth-required.test.tsx
Labels: review:small

#406 [SDK-2483] Add base path and i18n guidance
  README.md
Labels: review:small

#408 Release 1.4.0
  CHANGELOG.md
  docs/assets/js/search.js
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.baseconfig.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.nextconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_callback.callbackoptions.html
  docs/interfaces/handlers_login.authorizationparams.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  docs/modules/version.html
  package-lock.json
  package.json
  src/version.ts
Labels: review:small

#410 npm audit fix
  package-lock.json
Labels: review:tiny

#418 Add missing `default` keyword to doc snippets
  FAQ.md
  src/handlers/callback.ts
Labels: documentation, review:tiny

#426 Release 1.4.1
  CHANGELOG.md
  docs/assets/js/search.js
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.baseconfig.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.nextconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_callback.callbackoptions.html
  docs/interfaces/handlers_login.authorizationparams.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  docs/modules/utils_errors.html
  docs/modules/version.html
  package-lock.json
  package.json
  src/version.ts
Labels: review:tiny

#428 Replace prepublish with prepack
  package.json
Labels: review:tiny

#432 Add IE11 support [SDK-2629]
  package-lock.json
  src/utils/errors.ts
  tsconfig.build.json
Labels: CH: Added, review:small
