Repository auth0/nextjs-auth0, pull requests merged in 2022-04, with the labels that each got.

#641 Fix broken link to Vercel documentation
  examples/README.md
Labels: documentation, review:tiny

#639 Handle request errors on `useUser` hook [SDK-3227]
  src/frontend/index.ts
  src/frontend/use-user.tsx
  src/index.browser.ts
  src/index.ts
  tests/fixtures/frontend.tsx
  tests/fixtures/test-app/next-env.d.ts
  tests/frontend/use-user.test.tsx
  tests/frontend/with-page-auth-required.test.tsx
Labels: CH: Fixed, review:medium

#653 Fix Fast Refresh for WithPageAuthRequired
  src/frontend/with-page-auth-required.tsx
Labels: review:tiny
