Repository auth0/nextjs-auth0, pull requests merged in 2022-10, with the labels that each got.

#835 [SDK-3553] Improved callback errors
  FAQ.md
  src/auth0-session/handlers/callback.ts
  src/auth0-session/index.ts
  src/auth0-session/utils/errors.ts
  src/index.ts
  src/utils/errors.ts
  tests/auth0-session/handlers/callback.test.ts
  tests/fixtures/setup.ts
  tests/handlers/auth.test.ts
  tests/handlers/callback.test.ts
Labels: review:small

#838 [SDK-3567] Allow response customization in afterCallback
  V2_MIGRATION_GUIDE.md
  src/auth0-session/handlers/callback.ts
  src/handlers/auth.ts
  src/handlers/callback.ts
  tests/auth0-session/fixtures/helpers.ts
  tests/auth0-session/handlers/callback.test.ts
Labels: review:medium

#845 Add missing API docs for `OnError`
  src/handlers/auth.ts
Labels: documentation, review:tiny

#843 Fix updates to session not reflected in async `getServerSideProps`
  src/helpers/get-server-side-props-wrapper.ts
  tests/helpers/with-page-auth-required.test.ts
Labels: review:tiny

#844 Update Markdown documentation according to docs guidelines
  ARCHITECTURE.md
  EXAMPLES.md
  README.md
  examples/README.md
Labels: documentation, review:small

#847 Documentation updates for v1
  EXAMPLES.md
  package-lock.json
  package.json
  src/config.ts
Labels: review:tiny

#854 [SDK-3664] Merge `main` branch
  CHANGELOG.md
  EXAMPLES.md
  docs/assets/css/main.css
  docs/assets/js/main.js
  docs/assets/js/search.js
  docs/classes/frontend_use_user.requesterror.html
  docs/classes/session.sessioncache.html
  docs/classes/session_session.default.html
  docs/classes/utils_errors.accesstokenerror.html
  docs/classes/utils_errors.handlererror.html
  docs/interfaces/config.authorizationparameters.html
  docs/interfaces/config.baseconfig.html
  docs/interfaces/config.cookieconfig.html
  docs/interfaces/config.nextconfig.html
  docs/interfaces/config.sessionconfig.html
  docs/interfaces/frontend_use_user.userprofile.html
  docs/interfaces/frontend_with_page_auth_required.userprops.html
  docs/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
  docs/interfaces/handlers_auth.handlers.html
  docs/interfaces/handlers_callback.callbackoptions.html
  docs/interfaces/handlers_login.authorizationparams.html
  docs/interfaces/handlers_login.loginoptions.html
  docs/interfaces/handlers_logout.logoutoptions.html
  docs/interfaces/instance.signinwithauth0.html
  docs/interfaces/session_get_access_token.accesstokenrequest.html
  docs/interfaces/session_get_access_token.getaccesstokenresult.html
  docs/modules/config.html
  docs/modules/frontend.html
  docs/modules/frontend_use_user.html
  docs/modules/frontend_with_page_auth_required.html
  docs/modules/handlers_auth.html
  docs/modules/handlers_callback.html
  docs/modules/handlers_login.html
  docs/modules/handlers_logout.html
  docs/modules/handlers_profile.html
  docs/modules/helpers_get_server_side_props_wrapper.html
  docs/modules/helpers_with_api_auth_required.html
  docs/modules/helpers_with_page_auth_required.html
  docs/modules/instance.html
  docs/modules/session_get_access_token.html
  docs/modules/session_get_session.html
  docs/modules/utils_errors.html
  docs/modules/version.html
  package-lock.json
  package.json
  src/config.ts
  src/version.ts
  tests/helpers/with-page-auth-required.test.ts
Labels: review:small

#855 Change `updateUser` to `updateSession`
  README.md
  V2_MIGRATION_GUIDE.md
  src/index.browser.ts
  src/index.ts
  src/instance.ts
  src/session/index.ts
  src/session/update-session.ts
  src/session/update-user.ts
  tests/fixtures/global.d.ts
  tests/fixtures/setup.ts
  tests/fixtures/test-app/pages/api/update-session.ts
  tests/helpers/with-page-auth-required.test.ts
  tests/session/update-session.test.ts
Labels: review:small

#861 move encoding methods
  src/auth0-session/handlers/callback.ts
  src/auth0-session/handlers/login.ts
  src/auth0-session/hooks/get-login-state.ts
  src/auth0-session/utils/encoding.ts
  tests/auth0-session/handlers/callback.test.ts
  tests/auth0-session/handlers/login.test.ts
  tests/auth0-session/handlers/logout.test.ts
  tests/fixtures/setup.ts
  tests/handlers/callback.test.ts
  tests/handlers/login.test.ts
Labels: review:small

#862 Shouldn't serve routes for object builtins
  src/handlers/auth.ts
  tests/handlers/auth.test.ts
Labels: review:tiny

#865 npm audit fix
  package-lock.json
Labels: review:tiny

#867 [ASEC-892] Change insecure cookie from warning to error
  src/auth0-session/get-config.ts
  tests/auth0-session/config.test.ts
  tests/auth0-session/cookie-store.test.ts
  tests/auth0-session/transient-store.test.ts
Labels: review:small

#864 [ASEC-891] Escape idp error
  README.md
  src/auth0-session/client.ts
  src/auth0-session/handlers/callback.ts
  src/auth0-session/handlers/login.ts
  src/auth0-session/handlers/logout.ts
  src/auth0-session/utils/errors.ts
  src/utils/errors.ts
  tests/auth0-session/client.test.ts
  tests/auth0-session/handlers/callback.test.ts
  tests/auth0-session/utils/errors.test.ts
  tests/handlers/callback.test.ts
  tests/handlers/login.test.ts
  tests/utils/errors.test.ts
Labels: review:small

#871 Use latest ship-orb
  .circleci/config.yml
Labels: review:tiny

#875 status getter is not enumerable so needs to be added to NextResponse
  src/helpers/with-middleware-auth-required.ts
  tests/helpers/with-middleware-auth-required.test.ts
Labels: review:small

#877 Add logout options
  src/auth0-session/client.ts
  src/auth0-session/config.ts
  src/auth0-session/handlers/logout.ts
  src/handlers/logout.ts
  tests/auth0-session/handlers/logout.test.ts
  tests/handlers/logout.test.ts
Labels: review:small

#881 [SDK-3704] README Redesign
  EXAMPLES.md
  README.md
  SECURITY.md
  TESTING.md
Labels: review:medium

#886 Fix README links
  README.md
Labels: review:tiny

#888 Upgrade to openid-client@5
  README.md
  V2_MIGRATION_GUIDE.md
  package-lock.json
  package.json
  src/auth0-session/client.ts
  src/auth0-session/utils/errors.ts
  tests/auth0-session/client.test.ts
  tests/auth0-session/handlers/callback.test.ts
Labels: review:small
