Repository auth0/nextjs-auth0, pull requests merged in 2022-09, with the labels that each got.

#800 Allow to override the `user` prop in server-side rendered pages [SDK-3560]
  src/helpers/with-page-auth-required.ts
  tests/helpers/with-page-auth-required.test.ts
Labels: CH: Added

#796 Improve API docs [SDK-3562]
  package-lock.json
  package.json
  src/auth0-session/client.ts
  src/auth0-session/config.ts
  src/auth0-session/hooks/get-login-state.ts
  src/auth0-session/transient-store.ts
  src/auth0-session/utils/hkdf.ts
  src/config.ts
  src/frontend/use-user.tsx
  src/frontend/with-page-auth-required.tsx
  src/handlers/auth.ts
  src/handlers/callback.ts
  src/handlers/login.ts
  src/handlers/logout.ts
  src/handlers/profile.ts
  src/helpers/with-api-auth-required.ts
  src/helpers/with-page-auth-required.ts
  src/instance.ts
  src/session/get-access-token.ts
  src/session/session.ts
  src/session/update-user.ts
  src/utils/errors.ts
  src/utils/url-helpers.ts
  tests/auth0-session/handlers/callback.test.ts
  tests/handlers/profile.test.ts
  tests/helpers/with-page-auth-required.test.ts
  tests/setup.ts
Labels: review:large

#810 Fix v1 cookie tests
  tests/auth0-session/cookie-store.test.ts
Labels: review:tiny

#809 Do not store the ID token by default [SDK-3563]
  FAQ.md
  V2_MIGRATION_GUIDE.md
  src/auth0-session/config.ts
  src/auth0-session/get-config.ts
  src/config.ts
  src/session/session.ts
  tests/auth0-session/config.test.ts
  tests/config.test.ts
  tests/handlers/callback.test.ts
  tests/session/get-access-token.test.ts
  tests/session/session.test.ts
Labels: review:small, CH: Breaking Change

#815 [SDK-3554] Next.js Middlware support
  EXAMPLES.md
  README.md
  cypress/integration/smoke.test.ts
  examples/basic-example/next.config.js
  examples/kitchen-sink-example/middleware.ts
  examples/kitchen-sink-example/next.config.js
  examples/kitchen-sink-example/pages/profile-mw.tsx
  examples/kitchen-sink-example/pages/profile-ssr.tsx
  middleware.d.ts
  middleware.js
  package-lock.json
  package.json
  src/auth0-session/config.ts
  src/auth0-session/cookie-store.ts
  src/auth0-session/get-config.ts
  src/auth0-session/index.ts
  src/auth0-session/session-cache.ts
  src/auth0-session/transient-store.ts
  src/auth0-session/utils/cookies.ts
  src/config.ts
  src/frontend/use-user.tsx
  src/handlers/auth.ts
  src/handlers/callback.ts
  src/helpers/testing.ts
  src/helpers/with-middleware-auth-required.ts
  src/index.ts
  src/middleware.ts
  src/session/cache.ts
  src/session/get-session.ts
  src/session/session.ts
  src/session/update-user.ts
  src/utils/assert.ts
  src/utils/errors.ts
  src/utils/middleware-cookies.ts
  tests/auth0-session/config.test.ts
  tests/auth0-session/fixtures/server.ts
  tests/auth0-session/utils/cookie.test.ts
  tests/helpers/testing.test.ts
  tests/helpers/with-middleware-auth-required.test.ts
  tests/session/cache.test.ts
  tests/setup.ts
  tests/utils/middleware-cookies.test.ts
Labels: review:large

#818 Fix intermittent build issues
  package.json
Labels: review:tiny

#825 [SDK-3556] Prevent mixing named exports and own instances
  package.json
  src/index.ts
  src/middleware.ts
  src/utils/instance-check.ts
  tests/helpers/with-middleware-auth-required.test.ts
  tests/index.test.ts
Labels: review:medium

#823 [SDK-3559] Default error handler
  V2_MIGRATION_GUIDE.md
  examples/kitchen-sink-example/pages/api/auth/[auth0].ts
  package.json
  src/handlers/auth.ts
  src/handlers/index.ts
  src/index.ts
  tests/fixtures/global.d.ts
  tests/fixtures/setup.ts
  tests/fixtures/test-app/pages/api/access-token.ts
  tests/fixtures/test-app/pages/api/auth/[...auth0].ts
  tests/fixtures/test-app/pages/api/protected.ts
  tests/fixtures/test-app/pages/api/session.ts
  tests/fixtures/test-app/pages/api/update-user.ts
  tests/fixtures/test-app/pages/csr-protected.tsx
  tests/fixtures/test-app/pages/global.d.ts
  tests/fixtures/test-app/pages/protected.tsx
  tests/handlers/auth.test.ts
  tests/handlers/logout.test.ts
  tests/handlers/profile.test.ts
Labels: review:medium
