Repository auth0/nextjs-auth0, pull requests merged in 2023-01, with the labels that each got.

#993 SDK-3807 Add custom session stores
  EXAMPLES.md
  src/auth0-session/config.ts
  src/auth0-session/cookie-store.ts
  src/auth0-session/get-config.ts
  src/auth0-session/index.ts
  src/auth0-session/session/abstract-session.ts
  src/auth0-session/session/stateful-session.ts
  src/auth0-session/session/stateless-session.ts
  src/auth0-session/transient-store.ts
  src/auth0-session/utils/signed-cookies.ts
  src/config.ts
  src/edge.ts
  src/helpers/testing.ts
  src/index.ts
  src/session/cache.ts
  tests/auth0-session/fixtures/helpers.ts
  tests/auth0-session/fixtures/server.ts
  tests/auth0-session/handlers/callback.test.ts
  tests/auth0-session/session/stateful-session.test.ts
  tests/auth0-session/session/stateless-session.test.ts
  tests/auth0-session/transient-store.test.ts
  tests/handlers/callback.test.ts
  tests/helpers/testing.test.ts
  tests/helpers/with-middleware-auth-required.test.ts
  tests/session/cache.test.ts
  tests/stateful-session.test.ts
Labels: review:large

#1014 Infer user exists if WithPageAuthRequired page is rendered
  src/helpers/with-page-auth-required.ts
Labels: review:tiny

#1019 Fix middleware imports in API docs
  src/helpers/with-middleware-auth-required.ts
Labels: documentation

#1018 Update @types/node
  package-lock.json
  package.json
  tests/auth0-session/fixtures/server.ts
  tests/fixtures/global.d.ts
Labels: review:tiny

#1028 withMiddlewareAuthRequired returnTo should be a relative url
  src/helpers/with-middleware-auth-required.ts
  tests/helpers/with-middleware-auth-required.test.ts
Labels: review:small
